meta_product_name: "Q-LESS"
meta_title: "Q-LESS - Queue Less, Party More"
meta_description: "Find all types of events around you and check the live waiting time. Don't wait, dance!"
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
